# Do not change this.
config-version: 1.0

# Type of database to use, choose SQLITE for a local database and MYSQL if you use a MYSQL database
database-type: SQLITE

# This will only be used if you use MYSQL as database-type
host: localhost
port: 3306
database: database
username: username
password: password

table-prefix: 'sbananim_'

# The commands specified here will be watched for and will be used for the ban animations. This will ONLY work if the **first** argument is the player you are punishing.
# For example: /ban <player> <reason> will work. /ban <reason> <player> will NOT.
commands:
  - "ban"
  - "tempban"