name: S-BanAnimations
api-version: 1.16
version: '${project.version}'
main: com.stanexe.sbananimations.SBanAnimations
authors: [ StanEXE ]
website: stanexe.com
commands:
  bananimation:
    aliases:
      - bananim
      - bananimations
    description: 'Main command for SBanAnimations'
    usage: "/bananimation <animation>"